# Generated by Django 6.1.1 on 2026-09-04 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='inspiration_image_1',
            field=models.ImageField(blank=True, null=True, upload_to='inspiration/'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='inspiration_image_2',
            field=models.ImageField(blank=True, null=True, upload_to='inspiration/'),
        ),
    ]
