# Generated by Django 6.1.1 on 2026-09-04 10:14

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_appointment_inspiration_image_1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='walkin',
            name='finish_time',
        ),
        migrations.AlterField(
            model_name='walkin',
            name='start_time',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
    ]
